name = "mainichi-heritage-frontend"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = ".open-next/assets"

[vars]
NODE_ENV = "production"

[[rules]]
type = "ESModule"
globs = ["*.js", "*.mjs"]

# staging 設定
[env.staging]
name = "mainichi-heritage-frontend-stg"

[env.staging.assets]
directory = ".open-next/assets"

[env.staging.vars]
NODE_ENV = "production"