name = "mainichi-heritage-frontend"
compatibility_date = "2026-05-01"
workers_dev = true
main = ".open-next/server-functions/default/index.mjs"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
