name = "mainichi-heritage-frontend"
main = "./.open-next/server-functions/default/index.mjs"
compatibility_date = "2026-05-01"
compatibility_flags = ["nodejs_compat"]

upload_source_maps = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[alias]
"react-server-dom-webpack/client" = "./wrangler-noop.mjs"
"react-server-dom-webpack/server" = "./wrangler-noop.mjs"
"react-server-dom-webpack/server.node" = "./wrangler-noop.mjs"
"react-server-dom-webpack/static" = "./wrangler-noop.mjs"
"react-server-dom-turbopack/client" = "./wrangler-noop.mjs"
"react-server-dom-turbopack/server" = "./wrangler-noop.mjs"
"react-server-dom-turbopack/static" = "./wrangler-noop.mjs"
"react-dom/static" = "./wrangler-noop.mjs"
"./middleware.mjs" = "./wrangler-noop.mjs"
"critters" = "./wrangler-noop.mjs"
"@opentelemetry/api" = "./wrangler-noop.mjs"