# Generated by Django 6.0.3 on 2026-05-04 06:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='国コード')),
                ('name', models.CharField(max_length=100, verbose_name='国名')),
                ('region', models.IntegerField(choices=[(1, 'アジア・オセアニア'), (2, 'ヨーロッパ・北米'), (3, 'ラテンアメリカ・カリブ'), (4, 'アフリカ'), (5, 'アラブ諸国')], default=1, verbose_name='地域区分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '国マスタ',
                'verbose_name_plural': '国マスタ',
            },
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='登録基準コード')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='登録基準番号')),
                ('short_name', models.CharField(max_length=50, verbose_name='要約')),
                ('description', models.TextField(verbose_name='基準の内容')),
            ],
            options={
                'verbose_name': '登録基準',
                'verbose_name_plural': '登録基準マスタ',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(1, '重要'), (2, 'アップデート'), (3, '世界遺産追加'), (4, 'クイズ追加'), (5, '検定情報'), (9, 'その他')], default=9, verbose_name='カテゴリ')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='本文')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='公開日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'お知らせ',
                'verbose_name_plural': 'お知らせ一覧',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Heritage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='コード')),
                ('name', models.CharField(max_length=255, verbose_name='世界遺産名')),
                ('category', models.IntegerField(choices=[(1, '文化遺産'), (2, '自然遺産'), (3, '複合遺産')], verbose_name='カテゴリー')),
                ('catchphrase', models.CharField(blank=True, max_length=255, null=True, verbose_name='キャッチフレーズ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('registered_year', models.IntegerField(verbose_name='登録年')),
                ('level', models.IntegerField(choices=[(1, '4級'), (2, '3級'), (3, '2級'), (4, '準1級'), (5, '1級'), (6, 'マイスター')], default=2, verbose_name='対象級')),
                ('is_danger', models.BooleanField(default=False, verbose_name='危機遺産フラグ')),
                ('danger_registered_year', models.IntegerField(blank=True, null=True, verbose_name='危機遺産登録年')),
                ('is_negative_heritage', models.BooleanField(default=False, verbose_name='負の遺産フラグ')),
                ('is_cultural_landscape', models.BooleanField(default=False, verbose_name='文化的景観フラグ')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='画像URL')),
                ('source_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='出典元')),
                ('source_url', models.URLField(blank=True, null=True, verbose_name='出典元URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('countries', models.ManyToManyField(related_name='heritages', to='heritages.country', verbose_name='所在国')),
                ('criteria', models.ManyToManyField(related_name='heritages', to='heritages.criterion', verbose_name='登録基準')),
            ],
            options={
                'verbose_name': '世界遺産',
                'verbose_name_plural': '世界遺産一覧',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='クイズコード')),
                ('question', models.TextField(verbose_name='問題文')),
                ('choice_correct', models.CharField(max_length=255, verbose_name='正解')),
                ('choice_distractor1', models.CharField(max_length=255, verbose_name='不正解1')),
                ('choice_distractor2', models.CharField(max_length=255, verbose_name='不正解2')),
                ('choice_distractor3', models.CharField(max_length=255, verbose_name='不正解3')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='解説')),
                ('tips', models.TextField(blank=True, null=True, verbose_name='ヒント')),
                ('difficulty', models.IntegerField(choices=[(1, '4級'), (2, '3級'), (3, '2級'), (4, '準1級'), (5, '1級'), (6, 'マイスター')], default=1, verbose_name='難易度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('heritage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='heritages.heritage', verbose_name='対象の遺産')),
            ],
            options={
                'verbose_name': 'クイズ',
                'verbose_name_plural': 'クイズ一覧',
            },
        ),
    ]
