# Generated by Django 6.0.3 on 2026-03-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heritage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('country', models.CharField(max_length=100, verbose_name='所在国')),
                ('category', models.CharField(choices=[('CULTURAL', '文化遺産'), ('NATURAL', '自然遺産'), ('MIXED', '複合遺産')], max_length=20, verbose_name='分類')),
                ('description', models.TextField(verbose_name='概要')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='画像URL')),
                ('registered_year', models.IntegerField(blank=True, null=True, verbose_name='登録年')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '世界遺産',
                'verbose_name_plural': '世界遺産',
            },
        ),
    ]
