# Generated by Django 6.0.3 on 2026-05-06 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAnswerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_count', models.PositiveSmallIntegerField(default=0, verbose_name='回答回数')),
                ('correct_count', models.PositiveSmallIntegerField(default=0, verbose_name='正解回数')),
                ('is_latest_correct', models.BooleanField(default=False, verbose_name='直近で正解したか')),
                ('last_attempted_at', models.DateTimeField(auto_now=True, verbose_name='最終回答日時')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_histories', to='heritages.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'クイズ回答履歴',
                'verbose_name_plural': 'クイズ回答履歴一覧',
                'indexes': [models.Index(fields=['user', 'is_latest_correct'], name='heritages_q_user_id_d6a9ec_idx'), models.Index(fields=['user', 'last_attempted_at'], name='heritages_q_user_id_61174f_idx')],
                'unique_together': {('user', 'quiz')},
            },
        ),
    ]
