# Generated by Django 6.0.3 on 2026-03-21 06:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=10, unique=True, verbose_name='国コード')),
                ('name', models.CharField(max_length=100, verbose_name='国名')),
                ('region_id', models.IntegerField(choices=[(1, 'アジア・オセアニア'), (2, 'ヨーロッパ・北米'), (3, 'ラテンアメリカ・カリブ'), (4, 'アフリカ'), (5, 'アラブ諸国')], default=1, verbose_name='地域区分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria_no', models.IntegerField(verbose_name='登録基準番号')),
                ('description', models.CharField(max_length=255, verbose_name='概要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.AlterModelOptions(
            name='heritage',
            options={},
        ),
        migrations.RemoveField(
            model_name='heritage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='heritage',
            name='country',
        ),
        migrations.AddField(
            model_name='heritage',
            name='category_id',
            field=models.IntegerField(choices=[(1, '文化遺産'), (2, '自然遺産'), (3, '複合遺産')], default=1, verbose_name='カテゴリーID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='heritage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='作成日時'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='heritage',
            name='description_detail',
            field=models.TextField(blank=True, null=True, verbose_name='詳細'),
        ),
        migrations.AddField(
            model_name='heritage',
            name='is_danger',
            field=models.BooleanField(default=False, verbose_name='危機遺産フラグ'),
        ),
        migrations.AddField(
            model_name='heritage',
            name='is_level_1',
            field=models.BooleanField(default=False, verbose_name='1級フラグ'),
        ),
        migrations.AddField(
            model_name='heritage',
            name='is_level_2',
            field=models.BooleanField(default=False, verbose_name='2級フラグ'),
        ),
        migrations.AddField(
            model_name='heritage',
            name='is_level_3',
            field=models.BooleanField(default=False, verbose_name='3級フラグ'),
        ),
        migrations.AddField(
            model_name='heritage',
            name='is_level_4',
            field=models.BooleanField(default=False, verbose_name='4級フラグ'),
        ),
        migrations.AddField(
            model_name='heritage',
            name='is_level_pre1',
            field=models.BooleanField(default=False, verbose_name='準1級フラグ'),
        ),
        migrations.AddField(
            model_name='heritage',
            name='is_mister',
            field=models.BooleanField(default=False, verbose_name='マイスターフラグ'),
        ),
        migrations.AlterField(
            model_name='heritage',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='画像URL'),
        ),
        migrations.AlterField(
            model_name='heritage',
            name='registered_year',
            field=models.IntegerField(default=1, verbose_name='登録年'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='heritage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AddField(
            model_name='heritage',
            name='countries',
            field=models.ManyToManyField(related_name='heritages', to='heritages.country', verbose_name='所在国'),
        ),
        migrations.AddField(
            model_name='heritage',
            name='criteria',
            field=models.ManyToManyField(related_name='heritages', to='heritages.criterion', verbose_name='登録基準'),
        ),
    ]
