# Generated by Django 6.0.3 on 2026-03-21 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritages', '0002_country_criterion_alter_heritage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='問題文')),
                ('choice_correct', models.CharField(max_length=255, verbose_name='正解')),
                ('choice_distractor1', models.CharField(max_length=255, verbose_name='不正解1')),
                ('choice_distractor2', models.CharField(max_length=255, verbose_name='不正解2')),
                ('choice_distractor3', models.CharField(max_length=255, verbose_name='不正解3')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='解説')),
                ('difficulty_level', models.IntegerField(choices=[(1, '1級'), (15, '準1級'), (2, '2級'), (3, '3級'), (4, '4級')], default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('heritage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='heritages.heritage', verbose_name='対象の遺産')),
            ],
            options={
                'verbose_name': 'クイズ',
                'verbose_name_plural': 'クイズ一覧',
            },
        ),
    ]
