# Generated by Django 6.0.3 on 2026-05-06 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritages', '0002_quizanswerhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizanswerhistory',
            name='quiz',
            field=models.ForeignKey(db_column='quiz_code', on_delete=django.db.models.deletion.CASCADE, to='heritages.quiz', to_field='code'),
        ),
    ]
