# Generated by Django 6.0.3 on 2026-03-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritages', '0003_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='tips',
            field=models.TextField(blank=True, null=True, verbose_name='ヒント'),
        ),
    ]
