# Generated by Django 6.0.3 on 2026-05-06 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heritages', '0003_alter_quizanswerhistory_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizanswerhistory',
            name='attempt_count',
        ),
        migrations.RemoveField(
            model_name='quizanswerhistory',
            name='correct_count',
        ),
    ]
