# Generated by Django 6.0.3 on 2026-03-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritages', '0004_quiz_tips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heritage',
            name='is_level_4',
        ),
        migrations.AddField(
            model_name='heritage',
            name='source_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='出典元'),
        ),
        migrations.AddField(
            model_name='heritage',
            name='source_url',
            field=models.URLField(blank=True, null=True, verbose_name='出典元URL'),
        ),
    ]
