# Generated by Django 6.0.3 on 2026-03-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritages', '0005_remove_heritage_is_level_4_heritage_source_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heritage',
            old_name='is_mister',
            new_name='is_level_mister',
        ),
        migrations.AlterField(
            model_name='heritage',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='概要'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='difficulty_level',
            field=models.IntegerField(choices=[(1, '1級'), (15, '準1級'), (2, '2級'), (3, '3級')], default=2),
        ),
    ]
