# Generated by Django 6.0.3 on 2026-03-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritages', '0007_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heritage',
            name='criteria',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='region_id',
            new_name='region',
        ),
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='国コード'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_code',
            field=models.CharField(max_length=10, unique=True, verbose_name='旧国コード'),
        ),
        migrations.DeleteModel(
            name='Criterion',
        ),
    ]
