# Generated by Django 6.0.3 on 2026-03-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritages', '0008_remove_heritage_criteria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='country_code',
        ),
        migrations.AddField(
            model_name='heritage',
            name='level',
            field=models.IntegerField(choices=[(1, '4級'), (2, '3級'), (3, '2級'), (4, '準1級'), (5, '1級'), (6, 'マイスター')], default=2, verbose_name='対象級'),
        ),
    ]
