# Generated by Django 6.0.3 on 2026-03-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritages', '0009_remove_country_country_code_heritage_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heritage',
            name='is_level_1',
        ),
        migrations.RemoveField(
            model_name='heritage',
            name='is_level_2',
        ),
        migrations.RemoveField(
            model_name='heritage',
            name='is_level_3',
        ),
        migrations.RemoveField(
            model_name='heritage',
            name='is_level_mister',
        ),
        migrations.RemoveField(
            model_name='heritage',
            name='is_level_pre1',
        ),
        migrations.AddField(
            model_name='heritage',
            name='catchphrase',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='キャッチフレーズ'),
        ),
    ]
