# Generated by Django 6.0.3 on 2026-03-28 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heritages', '0010_remove_heritage_is_level_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heritage',
            name='description',
        ),
    ]
