# Generated by Django 6.0.3 on 2026-03-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritages', '0011_remove_heritage_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heritage',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='heritage',
            name='description_detail',
        ),
        migrations.AddField(
            model_name='heritage',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='heritage',
            name='name',
            field=models.CharField(max_length=255, verbose_name='世界遺産名'),
        ),
    ]
