# Generated by Django 6.0.3 on 2026-03-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritages', '0012_rename_category_id_heritage_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heritage',
            name='category',
            field=models.IntegerField(choices=[(1, '文化遺産'), (2, '自然遺産'), (3, '複合遺産')], verbose_name='カテゴリー'),
        ),
    ]
