# Generated by Django 6.0.3 on 2026-03-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritages', '0013_alter_heritage_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='question_text',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='difficulty_level',
        ),
        migrations.AddField(
            model_name='quiz',
            name='difficulty',
            field=models.IntegerField(choices=[(1, '4級'), (2, '3級'), (3, '2級'), (4, '準1級'), (5, '1級'), (6, 'マイスター')], default=1, verbose_name='難易度'),
        ),
    ]
