# Generated by Django 6.0.3 on 2026-03-28 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heritages', '0014_rename_question_text_quiz_question_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': '国マスタ', 'verbose_name_plural': '国マスタ'},
        ),
        migrations.AlterModelOptions(
            name='heritage',
            options={'verbose_name': '世界遺産', 'verbose_name_plural': '世界遺産一覧'},
        ),
    ]
