# Generated by Django 6.0.3 on 2026-03-29 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritages', '0015_alter_country_options_alter_heritage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='登録基準番号')),
                ('description', models.TextField(verbose_name='基準の内容')),
            ],
            options={
                'verbose_name': '登録基準',
                'verbose_name_plural': '登録基準マスタ',
            },
        ),
        migrations.AddField(
            model_name='heritage',
            name='criteria',
            field=models.ManyToManyField(related_name='heritages', to='heritages.criterion', verbose_name='登録基準'),
        ),
    ]
