# Generated by Django 6.0.3 on 2026-03-29 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritages', '0016_criterion_heritage_criteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='short_name',
            field=models.CharField(default=1, max_length=50, verbose_name='要約'),
            preserve_default=False,
        ),
    ]
