# Generated by Django 6.0.3 on 2026-04-12 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritages', '0017_criterion_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='登録基準コード'),
        ),
        migrations.AddField(
            model_name='heritage',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='コード'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='クイズコード'),
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(default='tmp', max_length=10, unique=True, verbose_name='国コード'),
            preserve_default=False,
        ),
    ]
