# Generated by Django 6.0.3 on 2026-04-12 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritages', '0018_criterion_code_heritage_code_quiz_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterion',
            name='code',
            field=models.CharField(default='tmp', max_length=10, unique=True, verbose_name='登録基準コード'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='heritage',
            name='code',
            field=models.CharField(default='tmp', max_length=50, unique=True, verbose_name='コード'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='code',
            field=models.CharField(default='tmp', max_length=20, unique=True, verbose_name='クイズコード'),
            preserve_default=False,
        ),
    ]
