# Generated by Django 6.0.3 on 2026-04-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritages', '0019_alter_criterion_code_alter_heritage_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heritage',
            name='danger_registered_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='危機遺産登録年'),
        ),
    ]
