# Generated by Django 6.0.3 on 2026-04-18 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritages', '0020_heritage_danger_registered_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='heritage',
            name='is_negative_heritage',
            field=models.BooleanField(default=False, help_text='戦争、人種差別、奴隷貿易など人類の悲劇を象徴する遺産', verbose_name='負の遺産フラグ'),
        ),
    ]
