# Generated by Django 6.0.3 on 2026-04-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritages', '0021_heritage_is_negative_heritage'),
    ]

    operations = [
        migrations.AddField(
            model_name='heritage',
            name='is_cultural_landscape',
            field=models.BooleanField(default=False, verbose_name='文化的景観フラグ'),
        ),
        migrations.AlterField(
            model_name='heritage',
            name='is_negative_heritage',
            field=models.BooleanField(default=False, verbose_name='負の遺産フラグ'),
        ),
    ]
