# Generated by Django 6.0.3 on 2026-04-30 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritages', '0022_heritage_is_cultural_landscape_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='heritage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='heritages.heritage', verbose_name='対象の遺産'),
        ),
    ]
