# Generated by Django 6.0.3 on 2026-04-30 06:41

from django.db import migrations

def format_quiz_codes(apps, schema_editor):
    Quiz = apps.get_model('heritages', 'Quiz')
    for quiz in Quiz.objects.all():
        # q-hXXXXX-XX の形式（3文字目がハイフンでない）場合に変換
        if quiz.code.startswith('q-h') and quiz.code[3] != '-':
            quiz.code = quiz.code.replace('q-h', 'q-h-', 1)
            quiz.save()

class Migration(migrations.Migration):

    dependencies = [
        ('heritages', '0023_alter_quiz_heritage'),
    ]

    operations = [
        migrations.RunPython(format_quiz_codes),
    ]
