# Generated by Django 6.0.3 on 2026-05-24 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heritages', '0024_auto_20260430_0641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heritage',
            name='image_url',
        ),
    ]
