# Generated by Django 6.0.3 on 2026-05-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritages', '0025_remove_heritage_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='heritage',
            name='description_1',
            field=models.TextField(blank=True, null=True, verbose_name='1級用解説'),
        ),
        migrations.AddField(
            model_name='heritage',
            name='description_1_pre',
            field=models.TextField(blank=True, null=True, verbose_name='準1級用解説'),
        ),
        migrations.AddField(
            model_name='heritage',
            name='description_2',
            field=models.TextField(blank=True, null=True, verbose_name='2級用解説'),
        ),
        migrations.AddField(
            model_name='heritage',
            name='description_3',
            field=models.TextField(blank=True, null=True, verbose_name='3級用解説'),
        ),
        migrations.AddField(
            model_name='heritage',
            name='description_4',
            field=models.TextField(blank=True, null=True, verbose_name='4級用解説'),
        ),
        migrations.AddField(
            model_name='heritage',
            name='description_m',
            field=models.TextField(blank=True, null=True, verbose_name='マイスター用解説'),
        ),
    ]
