# Generated by Django 6.0.3 on 2026-05-27 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritages', '0026_heritage_description_1_heritage_description_1_pre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heritage',
            name='description_1',
        ),
        migrations.RemoveField(
            model_name='heritage',
            name='description_1_pre',
        ),
        migrations.RemoveField(
            model_name='heritage',
            name='description_2',
        ),
        migrations.RemoveField(
            model_name='heritage',
            name='description_3',
        ),
        migrations.RemoveField(
            model_name='heritage',
            name='description_4',
        ),
        migrations.RemoveField(
            model_name='heritage',
            name='description_m',
        ),
        migrations.CreateModel(
            name='HeritageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=1, verbose_name='表示順')),
                ('section_type', models.CharField(choices=[('summary', '概要'), ('point', '注目ポイント'), ('exam_notes', '検定攻略メモ')], default='point', max_length=20, verbose_name='セクション種別')),
                ('target_level', models.IntegerField(blank=True, choices=[(1, '4級'), (2, '3級'), (3, '2級'), (4, '準1級'), (5, '1級'), (6, 'マイスター')], null=True, verbose_name='表示場所')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='セクションタイトル')),
                ('content', models.TextField(verbose_name='本文')),
                ('image_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='画像コード')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('heritage_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='heritages.heritage', to_field='code', verbose_name='世界遺産コード')),
            ],
            options={
                'verbose_name': '世界遺産解説セクション',
                'verbose_name_plural': '世界遺産解説セクション一覧',
                'ordering': ['heritage_code', 'sort_order'],
            },
        ),
    ]
