# Generated by Django 6.0.3 on 2026-05-27 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heritages', '0027_remove_heritage_description_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heritage',
            name='description',
        ),
    ]
