# Generated by Django 6.0.3 on 2026-05-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritages', '0028_remove_heritage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='heritagesection',
            name='source_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='出典元'),
        ),
        migrations.AddField(
            model_name='heritagesection',
            name='source_url',
            field=models.URLField(blank=True, null=True, verbose_name='出典元URL'),
        ),
        migrations.AlterModelTable(
            name='heritagesection',
            table='heritages_heritage_section',
        ),
    ]
